pipeline:
    name: pushusingapi
    identifier: api_artifact_push
    allowStageExecutions: false
    projectIdentifier: sample
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Build and Push jar
              identifier: Test_Build_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: build
                                identifier: deploy_jar
                                spec:
                                    connectorRef: docker
                                    image: maven
                                    command: |-
                                        pwd
                                        ls -ltr
                                    privileged: false
                                when:
                                    stageStatus: Success
                                failureStrategies: []
                  infrastructure:
                      type: VM
                      spec:
                          type: Pool
                          spec:
                              identifier: ubuntu_pool
              variables: []
    properties:
        ci:
            codebase:
                connectorRef: gitconnector
                build: <+input>
    variables:
        - name: pipelineVar
          type: String
          value: pipelineVarValue
